/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313", 
        "secondary": "#ffb4ab", 
        "surface-container-lowest": "#0e0e0e", 
        "inverse-surface": "#e5e2e1", 
        "tertiary-fixed-dim": "#b4c5ff", 
        "surface-variant": "#353534", 
        "secondary-fixed-dim": "#ffb4ab", 
        "on-secondary-fixed": "#410002", 
        "surface-container-highest": "#353534", 
        "tertiary-fixed": "#dbe1ff", 
        "inverse-on-surface": "#313030", 
        "primary-fixed-dim": "#ffb95f", 
        "primary-container": "#f59e0b", 
        "tertiary-container": "#94aeff", 
        "on-tertiary-fixed-variant": "#003ea8", 
        "on-primary": "#472a00", 
        "on-primary-container": "#613b00", 
        "on-tertiary-container": "#003ba1", 
        "on-primary-fixed": "#2a1700", 
        "on-secondary-container": "#ffc8c1", 
        "error-container": "#93000a", 
        "surface-tint": "#ffb95f", 
        "on-tertiary-fixed": "#00174b", 
        "secondary-fixed": "#ffdad6", 
        "background": "#131313", 
        "secondary-container": "#bb0112", 
        "on-background": "#e5e2e1", 
        "on-error-container": "#ffdad6", 
        "inverse-primary": "#855300", 
        "on-error": "#690005", 
        "surface-container-high": "#2a2a2a", 
        "on-primary-fixed-variant": "#653e00", 
        "outline": "#a08e7a", 
        "error": "#ffb4ab", 
        "on-tertiary": "#002a78", 
        "surface-container-low": "#1c1b1b", 
        "surface": "#131313", 
        "surface-bright": "#3a3939", 
        "surface-container": "#201f1f", 
        "tertiary": "#bccbff", 
        "primary-fixed": "#ffddb8", 
        "on-secondary-fixed-variant": "#93000b", 
        "on-surface": "#e5e2e1", 
        "primary": "#ffc174", 
        "on-surface-variant": "#d8c3ad", 
        "outline-variant": "#534434", 
        "on-secondary": "#690005"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline-sm": ["Montserrat", "sans-serif"],
        "headline-xl": ["Anton", "sans-serif"],
        "label-tag": ["Montserrat", "sans-serif"],
        "label-button": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-xl-mobile": ["Anton", "sans-serif"],
        "price-hero": ["Anton", "sans-serif"],
        "display-hero-mobile": ["Anton", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "display-hero": ["Anton", "sans-serif"],
        "headline-lg": ["Anton", "sans-serif"],
        "title-md": ["Montserrat", "sans-serif"],
        "body-sm": ["Montserrat", "sans-serif"]
      }
    }
  },
  plugins: [],
}
